export const LOGIN_USER = "LOGIN_USER"
export const REGISTER_USER = "REGISTER_USER"

export const ADD_SEGMENT_CHARACTERISTICS = "ADD_SEGMENT_CHARACTERISTICS"
export const ADD_COLORGRAM = "ADD_COLORGRAM"