export const LOGIN_USER = "LOGIN_USER"
export const REGISTER_USER = "REGISTER_USER"
export const USER_INFO_FROM_ASYNC_STORAGE = "USER_INFO_FROM_ASYNC_STORAGE"

export const ADD_SEGMENT_CHARACTERISTICS = "ADD_SEGMENT_CHARACTERISTICS"
export const ADD_CENTER_SEGMENT = "ADD_CENTER_SEGMENT"
export const ADD_COLORGRAM = "ADD_COLORGRAM"

