export const LOGIN_USER = "LOGIN_USER"
export const REGISTER_USER = "REGISTER_USER"
export const USER_INFO_FROM_ASYNC_STORAGE = "USER_INFO_FROM_ASYNC_STORAGE"

export const ADD_SEGMENT_CHARACTERISTICS = "ADD_SEGMENT_CHARACTERISTICS"
export const ADD_CENTER_SEGMENT = "ADD_CENTER_SEGMENT"
export const ADD_COLORGRAM = "ADD_COLORGRAM"

export const CHANGE_TEXT_COLOR = "CHANGE_TEXT_COLOR"
export const CHANGE_FIRST_DIAG_SEGMENT = "CHANGE_FIRST_DIAG_SEGMENT"

export const LOAD_DEFAULT_DIAG = "LOAD_DEFAULT_DIAG"